services:
  - type: web
    name: transpell-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    runtime: python3.11
